### ISSUE TITLE
Check if GetBody in your SetEquipment hook was successful

### ISSUE THREAD

**Issue by WolfgangIsBestWolf** [bbborbo/ArtificerExtended#1]
I use SetEquipment in my mods a lot when only the master is present and for some of those things there's no work around to wait until a body exists.  
In your hook there's no double check if there is a Body and thus causes a NullRef. 
The incompatibility is usually a run ender so it'd be nice if you could fix it because people probably wouldn't wanna uninstall a huge content mod.

**Comment by bbborbo** [comment]
removed equipment functionality entirely for 3.2.0
