### ISSUE TITLE
Particles left behind from Energetic Resonance: Lightning bolts for non hosts on Multiplayer

### ISSUE THREAD

**Issue by Simpada** [bbborbo/ArtificerExtended#12]
For players that are not hosting, whenever an artificer fire Lightning Bolts, purple, star like particles are left behind. These particles are permanent, staying for the entire duration of the level. This is especially notable with Charged Nano-Bomb and Ion Surge, which both spawns alot of bolts. These leave behind a whole cluster of permanent particles.

**Comment by FreezyMLGNoob** [comment]
I'm having the exact same issue, it only affects the non host players

**Comment by bbborbo** [comment]
i think i found the source of the error and fixed it for the next update! thanks!

**Comment by jeanys** [comment]
This problem still exists on 3.6.6, and it seems to only occur when using the new passive skill.
