### ISSUE TITLE
HIFUArtificerTweaks Mod Incompatibility

### ISSUE THREAD

**Issue by BellaRoka** [bbborbo/ArtificerExtended#13]
The "Flamewall" ability from [HIFUArtificerTweaks](https://thunderstore.io/package/HIFU/HIFUArtificerTweaks/) does not add to the Energetic Resonance incinerate stacks (basically it doesn't seem to be recognized as a FIRE skill) and as such instead of getting the x4 per cast with having a full FIRE loadout you only get x3.

**Comment by bbborbo** [comment]
thanks, hifu fixed it!
