### ISSUE TITLE
Fully charging Channeled Nano-Meteor immediately uses a second stock

### ISSUE THREAD

**Issue by Fawkstrot11** [bbborbo/ArtificerExtended#14]
When using Channeled Nano-Meteor, fully charging the ability causes it to immediately fire, much like the base game Nano Abilities. However, the ability is missing the mustKeyPress property, so a second Meteor will begin charging immediately upon the first one being fired, unlike base Nano abilities which do not begin charging until the key is pressed again. This makes it extremely difficult to fire just a single fully charged meteor, and often leads to wasting a second stock on very little damage.

I _believe_ the windDownDuration check is meant to counteract this behavior, if I am reading the code correct, but 0.5f is a very, very tight window- too tight to reasonably expect people to release a button in while they focus on other things.

Adding mustKeyPress is the cleanest solution, but I frankly cannot find where the ability traits are, so increasing the windDownDuration by a decent margin (at least double, likely more) _may_ prove sufficient (assuming it does what I think it does?)

**Comment by bbborbo** [comment]
thanks, fixed!
