### ISSUE TITLE
Multiplayer issues

### ISSUE THREAD

**Issue by TenebrisN** [bbborbo/ArtificerExtended#16]
Lighting passive makes any projectile in game (as well as items) sometimes freeze in place forever, resulting in whole level being in visions of heresy shots, nano bombs, blind pests spits and other projectiles hovering in the air around causing insane lags, sometimes even crashes. Also items that you pick sometimes leave a coppy on the ground that will stay there forever. All this visible only for clients, host dont experience any issues until very late, then their fps gets bonked down heavily.

**Comment by Mishkia** [comment]
I'm running into a similar issue, though its only purple bolts from the vision of heresy. They appear after the spears have fired. Jade Alchemist is the host whereas I'm the client.
![image](https://github.com/bbborbo/ArtificerExtended/assets/119860250/e9f20086-c06e-4a4f-a54b-8f578a4069af)
![image](https://github.com/bbborbo/ArtificerExtended/assets/119860250/5eeb3d07-73f3-46e6-948e-5b1c197c440a)

**Comment by Simpada** [comment]
I have the same issue
