### ISSUE TITLE
Achievements no longer populating in logbook (and thus can't be acquired) 

### ISSUE THREAD

**Issue by Cyberson** [bbborbo/ArtificerExtended#3]
As of Patch v1.2.3 (Build ID #8537997) the coding for modded achievements changed and thus the alternate skills are no longer able to be unlocked. The previously unlocked ones are still intact, but unlocking any new ones is non-functional.

![Artificer Extended Skills](https://user-images.githubusercontent.com/7257082/166086206-afc50efe-e576-4a77-bbbb-6c97f68cae29.png)
![Artificer Challenges](https://user-images.githubusercontent.com/7257082/166086204-0237a45f-0835-4143-b717-004616e35238.png)

**Comment by bbborbo** [comment]
I know
