### ISSUE TITLE
Bug] Game freeze and log spam

### ISSUE THREAD

**Issue by breadguy69** [bbborbo/ArtificerExtended#6]
I believe it may be an interaction with AspectAbilities' glacial ability that disables skills. Log spams the ER info log like every frame. Full log:

[zipped_log.zip](https://github.com/bbborbo/ArtificerExtended/files/9996178/zipped_log.zip)

**Comment by breadguy69** [comment]
more info: happens in both sp and mp, with either passive enabled

**Comment by bbborbo** [comment]
i think i fixed this with 3.4.0
