### ISSUE TITLE
Missing Passive and Reworked Ion Surge

### ISSUE THREAD

**Issue by bmino** [bbborbo/ArtificerExtended#8]
After updating from version 3.3.3 (thunderstore) to 3.4.0 the alternative passive option is no longer present and ion surge has reverted to the vanilla version. Is this intentional? Sure was a cool idea and the reworked ion surge is amazing!

*the alt passive and reworked ion surge are also missing in 3.4.1*

**Comment by Delfofthebla** [comment]
In the patch notes on thunderstore it says that they were moved to a "new mod", but I don't see any reference to this mod anywhere. Not on the thunderstore, not on bbborbo's github. I don't understand why these were removed.

**Comment by bbborbo** [comment]
> In the patch notes on thunderstore it says that they were moved to a "new mod", but I don't see any reference to this mod anywhere. Not on the thunderstore, not on bbborbo's github. I don't understand why these were removed.

wrong version. the patch notes for version 3.4.0 clearly state that a few bugs were fixed, including the one that caused a new passive and ion surge rework to appear. rest assured, these bugs will not cause anyone any more trouble!
